### ISSUE TITLE
Can't get the extension to run a macro

### ISSUE THREAD

**Issue by jserenson** [jsnee/vscode-editor-macros#1]
I have installed the extension.
I edited editormacros in settings.json with the sample from the extension

{
    "editormacros": {
        "addSemicolon": {
            "type": "command",
            "args": {
                "commands": [
                    "cursorEnd",
                    {
                        "command": "type",
                        "args": {
                            "text": ";"
                        }
                    }
                ]
            }
        }
    }
}

So from here I  opened a file, placed the cursor, and did shift cmd P to open command pallette
and selected Run a Macro
A blank box came up with no macro to select to run.
I must admit it took a lot of work to find what commands to run.
But then I found in the command pallete List all the commands that can be used in macros.

What am I doing wrong.
Should I see a new macro addSemicolon when I select Run a macro in the command pallete

I really would like to get this going.
Thanks Jim S.

**Comment by jserenson** [comment]
It looks like I have to assign the macro to a keybinding to get it to work.
It would be helpful to have more information on how to write the macros.
there is only 3 samples. 
If you have other scenarios, how do you know how to proceeed. ??

**Comment by jserenson** [comment]
Is there more detailed information on writing the macros ??
Please advise. Thanks

**Comment by jsnee** [comment]
Sorry, I'm just seeing this. Yes, unfortunately with how VSCode works at the moment, the macros won't show up in the command palette and must be assigned to keyboard shortcuts to use. At the moment, this extension supports running VSCode commands ([here](https://code.visualstudio.com/api/references/commands) are some built in commands, but this list isn't comprehensive and commands can also be added by other extensions you have installed) and doing text replacement (the text replacement is covered in the README). As far as what commands are available, most things you find in the command palette should have a command "identifier". The trick is finding that identifier and how to use the command (some are straightforward, but others might take in arguments passed to them) and, unless you're using a command in the link I listed above, most commands aren't well documented, unfortunately. Oh, I did happen to find [this](https://gist.github.com/skfarhat/4e88ef386c93b9dceb98121d9457edbf) list someone compiled of all the built in commands.

Hopefully all that answers your questions? If not, feel free to follow up with anything else!

**Comment by jsnee** [comment]
If you have any specific macros in mind that you're trying to create, I could maybe take a whack at trying to help you write them, too.

**Comment by jserenson** [comment]
Joe:
Thank you so much for getting back to me.
I will be able to get through it slowly with the information.

Thanks Jim and Josephine

**Comment by jsnee** [comment]
Sounds good! Don't hesitate to let me know if you have any other questions!

**Comment by jserenson** [comment]
Hi Joe:
Sorry I have been busy with some other things, and have just gotten back to the macros.
I have been able to write a couple of macros, and make it work.
But now I have a question.
I have the code in the workspace settings.
I wanted to use the macro in another workspace.
I thought maybe I could put it in the user settings so I could run them no matter what workspace I have open.
when I did this I got a could not find the macro.
Is this possible to do ??

Thanks Jim and Josephine

**Comment by jsnee** [comment]
That should be able to work just fine, that's how I have mine configured. To help try to figure out what your issue might be, could you double check the following:
- The macro is spelled the same in the keybindings as it is in the settings
- Make sure `editormacros` section of the settings file in your workspace isn't `"editormacros": null`
  - Either remove it or make it an empty object: `"editormacros": {}`
  - It's also okay if it has it's own content, just make sure it isn't `null`
- Make sure none of the settings files have more than one `editormacros` section

Let me know if that does or doesn't help you out!

**Comment by jserenson** [comment]
Hi Joe:
Thanks for the input.
I checked all the files and changed the null to {}, and moved the editor macros code back to the user file.
And now everything works.
I think there was also an invalid value in one of the files.
I fixed that and now all seems to be okay.

Thanks Jim and Josephine

**Comment by jsnee** [comment]
Glad to be of help!

**Comment by Fxiao1** [comment]
Could you please add the ability to invoke macros through commands in the future? After all, when I create many macros, it is difficult for me to bind a shortcut key for each of them. And even if I do bind them, I may forget what shortcut keys I bound when I need to use them. So I hope there can be a list for me to choose which macro to run. Finally, thank you very much for developing this plugin, it has been a great help to me.

**Comment by jserenson** [comment]
Hi Joe
I am trying to write a macro and want to send text print(f"


Thanks Jim

**Comment by jserenson** [comment]
Hi Joe:
I have figured it out.

\"

Thanks Jim and Josephine
